name: NestJS E2E Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Run E2E Tests
      run: npm run test:e2e

    - name: Stop NestJS Application
      run: npm run stop
